### ISSUE TITLE
About ignore single item

### ISSUE THREAD

**Issue by moon5ckq** [xxr3376/Learn-Project#15]
希望可以加入忽略单个作业、通知、文件的功能

**Comment by Harry-Chen** [comment]
<del>由于 issue 提出者毕业而咕咕咕</del>
我调查了一下，大部分同学们认为没有必要（可以脑补忽略），因此就不作为目前比较紧急的需求了
不过的确有时候一个不需要交的作业一直在那里是挺头痛的，因此接下来可以考虑实现
