### ISSUE TITLE
Add support for learn v2

### ISSUE THREAD

**Issue by chenxiaoqino** [xxr3376/Learn-Project#16]
New version of learn website is located at [http://learn.cic.tsinghua.edu.cn/](http://learn.cic.tsinghua.edu.cn/). It is rumored that this website has a set of standard API for developers (URLunknown).

As of Feb 2014, as said by one teacher using it, one course can only use either the new version website or the old one. I.e., the data on two websites are completely separated.

Please consider adding data fetching script for new website.
Also, during the migration period, some course will operate on both site. It's necessary to distinguish and merge the items appropriately.

Since the new website is still in beta, I personally don't recommend working intensively for it now; however, all courses will eventually migrate everything onto it, and the Learn-Helper should work for it sooner or later.

**Comment by Harry-Chen** [comment]
learn 2015 is now deprecated
