### ISSUE TITLE
Firefox Support Needed

### ISSUE THREAD

**Issue by meowtech** [xxr3376/Learn-Project#19]
看见你们的工作，真心觉得很赞，身为firefox的重度用户，也想体验到你们的杰作，所以希望早日添加支持。

**Comment by Harry-Chen** [comment]
有计划实现一个 Electron 的版本，所以就不单独增加浏览器支持了。

**Comment by RikaSugisawa** [comment]
> 
> 
> 有计划实现一个 Electron 的版本，所以就不单独增加浏览器支持了。

现在Firefox和Chrome的附加组件已经基本上统一了。我尝试了一下在FF中使用，目前只发现下载文件时会破坏当前页面的显示内容，其余功能似乎没有什么影响。如果有空的话我可能会做一下FF的适配。

**Comment by Harry-Chen** [comment]
@RikaSugisawa 感谢，下载文件我是直接使用 `location.href` 进行重定向，由于服务器使用 `Content-Disposition` 头进行文件传送，Chrome 可以正常认为是文件下载。不知道 FF 是怎么处理的，一个 Fallback 方案是直接弹出一个新窗口。

**Comment by RikaSugisawa** [comment]
> 
> 
> @RikaSugisawa 感谢，下载文件我是直接使用 `location.href` 进行重定向，由于服务器使用 `Content-Disposition` 头进行文件传送，Chrome 可以正常认为是文件下载。不知道 FF 是怎么处理的，一个 Fallback 方案是直接弹出一个新窗口。

Firefox提示下载事件，同时页面上的内容清空。我的想法也是在新标签页打开，不知道还有没有什么其他的方案。

**Comment by Harry-Chen** [comment]
我找到了一个 WebExtension API: `browser.downloads`，在 [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) 有说明
用这个 API 或许可以解决这些问题（还可以顺便把插件里面用到的 `chrome` 换成 `browser`）

**Comment by Harry-Chen** [comment]
如果你有空的话可以修改一下

**Comment by RikaSugisawa** [comment]
好的，有空了我尝试一下

**Comment by function2-llx** [comment]
似乎本应用在 firefox 下架了，请问现在只能手动安装 unpacked 版本了吗？

**Comment by Harry-Chen** [comment]
@function2-llx 可以安装 self-hosted 版本，也会自动更新。请参见 <https://harrychen.xyz/learn> 相关说明。
