### ISSUE TITLE
网络错误：网络似乎出了一点小问题

### ISSUE THREAD

**Issue by jas0n1ee** [xxr3376/Learn-Project#21]
最近Learn Helper总是登陆不上，在win8.1和mac下的chrome都试过了。清空了缓存也重置了用户名密码，依然不行。。chrome 版本是41.0.2272.118 m....

**Comment by xxr3376** [comment]
网络学堂一直在做小幅改动，导致这边LearnHelper维护跟不上了，所以正常使用收到了影响。

我已离开学校，目前处于无人维护状态。。。

2015-04-09 0:58 GMT+08:00 Jason Lee <notifications@github.com>:

> 最近Learn Helper总是登陆不上，在win8.1和mac下的chrome都试过了。清空了缓存也重置了用户名密码，依然不行。。chrome
> 版本是41.0.2272.118 m....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xxr3376/Learn-Project/issues/21>.
>



-- 
此致！
祝福一切顺利！

  By UltimateGeeker

清华大学 计05 许欣然
xxr3376@gmail.com
13439689801

**Comment by yht1995** [comment]
@jas0n1ee 似乎是新版网络学堂改成了每次都要重新登录导致
你可以帮我再测试一下 https://github.com/xxr3376/Learn-Project/pull/23 
目前也不清楚有没有进一步的问题

**Comment by xxr3376** [comment]
感谢 @yht1995 @jas0n1ee ，麻烦两位做一下测试，如果基本正常的话，我会merge并发布更新版本。

另外如果愿意的话，请留下姓名、邮箱等联系方式，我在Release log中写上。

**Comment by jas0n1ee** [comment]
mac 上的chrome测试课件下载、通知和作业都没有问题 @xxr3376

**Comment by yht1995** [comment]
@xxr3376 目前应该是可以正常使用了，问题就是没有了延迟刷新的功能，每次打开就会重新登录。

**Comment by xxr3376** [comment]
OK，稍后会进行merge和发布。
麻烦你修改下感谢页面~把你自己加进去之后再发个Pull Request吧

在 2015年4月11日 下午12:02，yaoht <notifications@github.com>写道：

> @xxr3376 <https://github.com/xxr3376>
> 目前应该是可以正常使用了，问题就是没有了延迟刷新的功能，每次打开就会重新登录。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xxr3376/Learn-Project/issues/21#issuecomment-91756248>
> .
>



-- 
此致！
祝福一切顺利！

  By UltimateGeeker

清华大学 计05 许欣然
xxr3376@gmail.com
13439689801

**Comment by yht1995** [comment]
小改动用不着写了，你直接打包吧，好几个同学一直在说不能用来着
