### ISSUE TITLE
添加旁听学生账户支持

### ISSUE THREAD

**Issue by baishuai** [xxr3376/Learn-Project#27]
之前本科在清华学生的时候，就一值使用这个插件，非常棒。
目前在某研究所读研，研一的课程都在清华进修，使用旁听生的网络学堂帐号无法登录这个插件。
希望能够解决这个问题。
PS：如果需要旁听生的帐号进行调试，可以单独联系我。

**Comment by Harry-Chen** [comment]
目前这个问题应该解决了，4.0.0 开始走的是学校的统一认证接口
