### ISSUE TITLE
“在新窗口中打开”无法显示课程公告

### ISSUE THREAD

**Issue by wuqiling97** [xxr3376/Learn-Project#30]
![image](https://user-images.githubusercontent.com/19304928/38776580-b2df4f46-40cb-11e8-8572-d8c13a82ae8b.png)

对于使用旧版网络学堂的课程，在上图当中点击“在新窗口中打开”后，弹出的标签页当中没法显示课程公告。

原因：弹出网页使用的是https协议，但是课程公告是使用http加载的，而这个行为被chrome阻止了。

解决方案：将const.js当中的window.URL_CONST['course_page']字符串的'https'改为'http'

**Comment by xxr3376** [comment]
@wuqiling97 能否贡献一个 Pull request 呢？我已经离校多年，不再维护这个项目了。

**Comment by wuqiling97** [comment]
#31 已经创建好PR了
