### ISSUE TITLE
前端宽度适配

### ISSUE THREAD

**Issue by IrisLi17** [xxr3376/Learn-Project#35]
pane content有时会超出屏幕宽度，不太美观
![image](https://user-images.githubusercontent.com/28811555/53230717-4030b500-36c2-11e9-826c-ed44ad8c9557.png)

(https://github.com/xxr3376/Learn-Project/blob/97459f33d20d618c0ab1747f8fbf26ccb6371976/src/css/main.css#L134)

**Comment by Harry-Chen** [comment]
对，这个的确是特意做的，是怕太窄了以后布局变形过度。
我的确不怎么会设计UI，如果你有什么好的建议也可以一起 PR？

**Comment by xxr3376** [comment]
@Harry-Chen 请使用 css 的 media query 针对不同分辨率的宽度设置不同的 min-width 和 margin。

**Comment by Harry-Chen** [comment]
我目前使用了 media query 进行了一些调整，保证 >1024 宽度时显示比较正常，< 1024 的时候不可避免要滚动，否则的确是不太好看。以及我发现太长的 URL 的 wrap 有问题，可能是浏览器实现问题。目前没有太过影响使用的感受。
