### ISSUE TITLE
无法下载课程公告中的文件

### ISSUE THREAD

**Issue by zhaoxh16** [xxr3376/Learn-Project#36]
![_20190223194142](https://user-images.githubusercontent.com/23635588/53286014-11d6d680-37a3-11e9-82e1-54e8c66398ce.png)
当打开课程公告，并下载课程公告中的文件时，会显示错误“找不到您的文件，该文件可能已被移至别处或遭到删除。”

**Comment by Harry-Chen** [comment]
已查明错误来自于 thu-learn-lib 的解析
