### ISSUE TITLE
Feature Request: 去除课程公告内的空行

### ISSUE THREAD

**Issue by gaoyichuan** [xxr3376/Learn-Project#37]
有很多老师在填写课程公告的时候会加入大量空行，导致 Learn Helper 中公告内容显示观感比较差，希望能去除空行（包括内容只有 whitespace 的行）

PS：貌似大部分空行来自浏览器给 `<p>` 增加的样式

**Comment by Harry-Chen** [comment]
这个是 whitespace: pre-wrap 带来的问题，事实上不太好识别什么是“空行”，比如 `<p />`, `<span />`, `<br />` 都有可能带来空白的段落。我现在直接把HTML嵌入到页面中渲染，所以不太好控制最后究竟是什么样的。或许可以给这些元素加上一些样式来 workaround

**Comment by jiegec** [comment]
替换连续的换行？

**Comment by Harry-Chen** [comment]
@jiegec 目前能做的就只有把 `\n` 之类的替换掉，其他的基本都无能为力了

**Comment by Harry-Chen** [comment]
目前测试表明，去掉 `pre-wrap` 效果似乎好一些， @gaoyichuan 不妨验证一下？

**Comment by gaoyichuan** [comment]
测试了一下，去除 `pre-wrap` 的确可以让渲染效果更正常
