### ISSUE TITLE
Feature Request: 单击文件卡片的时候不直接下载

### ISSUE THREAD

**Issue by IcicleF** [xxr3376/Learn-Project#38]
* 一些课程文件有简介，这个简介只能在文件卡片底部显示，一般显示不全。
* 另外单击文件卡片就会直接下载文件，这个feature从3.x.x其实就有点想吐槽，有的时候点一个文件真的不是为了下载它而只是为了清未读标记而已...

综上，是否能提供单击文件不直接下载，而是在右边显示简介的feature
也可以为这个功能引入一个开关

**Comment by Harry-Chen** [comment]
嗯，我感觉这的确需要改进一下。不过清除已读标记其实有对应的按钮

**Comment by Harry-Chen** [comment]
Fixed by #39
