### ISSUE TITLE
重复打开时新标签数会指数上涨

### ISSUE THREAD

**Issue by rcy17** [xxr3376/Learn-Project#40]
正常情况下点击插件相应按钮chrome会打开一个新标签来运行插件，但是当我已经打开一个learnhelp时，再点几次按钮，会依次出现2、4、8、16个新标签，虽然也无伤大雅，甚至不知道算不算bug，不过要是是bug的话还是希望修复一下

**Comment by Harry-Chen** [comment]
这肯定是个bug，可以复现。但是不知道为什么……需要研究一下

**Comment by rcy17** [comment]
补充一句，经过进一步测试，如果我已经打开了n个标签，点击按钮会新产生n+1个

**Comment by Harry-Chen** [comment]
考虑下一个版本改成单例的
