### ISSUE TITLE
dist目录文件缺失

### ISSUE THREAD

**Issue by rcy17** [xxr3376/Learn-Project#45]
我没理解错的话，dist文件内容理应和release内容一致，但是看上去似乎缺少了`background.js`和`index.js`，导致试图直接clone项目从dist导入添加插件的话会提示文件缺失

**Comment by jiegec** [comment]
nope, 需要运行 npm build 啊

**Comment by Harry-Chen** [comment]
这两个文件是编译结果，不应该被添加在 git 中。
