### ISSUE TITLE
建议：三栏的滚动条分别滚动

### ISSUE THREAD

**Issue by Leojc** [xxr3376/Learn-Project#47]
目前我这里是第一、二栏是同时滚动的，这样子导致切换课程，查看公告，需要来回的上下滚动。
（Firefox Add-ons 版，4.0.3）
谢谢作者~

**Comment by Harry-Chen** [comment]
其实的确是分别滚动的（Chrome 正常），我过一阵子会集中解决一下 FF 上的问题

**Comment by Leojc** [comment]
原来如此，多谢
