### ISSUE TITLE
作业内容会超出宽度

### ISSUE THREAD

**Issue by renzibei** [xxr3376/Learn-Project#49]
公告等的文字宽度正常，但是作业的文字介绍会超出。
<img width="1672" alt="2019-02-28 19 22 09" src="https://user-images.githubusercontent.com/31380016/53563515-378f2180-3b8f-11e9-866c-dc0ff9161c97.png">

**Comment by gaoyichuan** [comment]
在最新版（4.0.3）通过审查元素的方式没能成功复现这个问题，请问你的插件版本号是？

**Comment by jiegec** [comment]
可以复现。4.0.3 同样是这个作业。

**Comment by renzibei** [comment]
4.0.3的版本出现该问题，用的mac的最新chrome

**Comment by renzibei** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/31380016/53734210-3bd47b00-3ebe-11e9-93e7-2c4610eba4fc.png">
贴上html，经检查，原网页中就存在那很多的<span>
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/31380016/53734466-0a0fe400-3ebf-11e9-9c90-3af5c914ed93.png">

其他的作业不一定会出现这种问题
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/31380016/53734354-b3a2a580-3ebe-11e9-8f01-fbd3917302b2.png">

**Comment by Harry-Chen** [comment]
这个其实没有很好的办法，因为网络学堂的作业经过了编辑器以后带上了比较多奇怪的 HTML tag 和样式，如果不尊重的话，就可能导致表格等内容不正常；如果按照原样显示，就会发生现在这个情况。不管是 wrap 还是不 wrap 都会不可避免出现问题。

**Comment by renzibei** [comment]
能不能过滤除了表格、段落等以外的tag

**Comment by Harry-Chen** [comment]
就你目前这个例子而言，span 也表示文本块。HTML 的标签没有严格的语义，配合 CSS 能够得到任意的样式，我认为贸然过滤不可取
