### ISSUE TITLE
建议：在首页添加链接到learn.tsinghua.edu.cn的链接

### ISSUE THREAD

**Issue by mhy12345** [xxr3376/Learn-Project#50]
有些时候想从插件页面跳转到learn.tsinghua.edu.cn网站，但是在插件页面上找不到可以快速跳转的方法。

**Comment by Harry-Chen** [comment]
每个课程都有”课程主页“可以跳过去

**Comment by mhy12345** [comment]
点击课程主页之后，页面是在一个iframe里面打开的，大小只有浏览器窗口的1/2，看起来非常不方便

**Comment by Harry-Chen** [comment]
@mhy12345 点击右侧栏左上角的按钮即可全屏。
