### ISSUE TITLE
“通过”显示为“-60”

### ISSUE THREAD

**Issue by tarawa** [xxr3376/Learn-Project#51]
查看作业成绩时，若成绩为“通过”则会显示为-60分。

**Comment by shyoshyo** [comment]
另外，没有批阅但没有给成绩时，显示 undefined

![image](https://user-images.githubusercontent.com/5780122/54181732-7485dd00-44da-11e9-9974-d838c889074c.png)

**Comment by Harry-Chen** [comment]
corner case 实在是太多了…记下了……一起修

**Comment by Harry-Chen** [comment]
目前看来批阅的作业至少有四种状态：
* 已阅：-1
* 通过：-60
* 正常：（相应分数）
* 不给成绩： undefnied

**Comment by Harry-Chen** [comment]
![image](https://user-images.githubusercontent.com/2819727/54205021-72d70c00-4510-11e9-92f8-827721295c28.png)

这个是网络学堂的非分值作业批改选项，每一个option都对应一个负数…

**Comment by tarawa** [comment]
欸。。那等级和百分是怎么对应的。。

**Comment by Harry-Chen** [comment]
认真分析了网络学堂的前端，对应关系为：

* -100 已阅
* -99 A+
* -98 A
* -92 A-
* -87 B+
* -82 B
* -78 B-
* -74 C+
* -71 C
* -68 C-
* -66 D+
* -64 D
* -30 F
* -51 I
* -62 EX
* -63 P
* -31 F,N/A
* -50 缓考
* -61 免修
* -85 优秀
* -60 通过
* -59 不通过
* -65 免课
* -55 W
* -67 G

我现在有些懵逼……

**Comment by Harry-Chen** [comment]
将在 `thu-learn-lib` 下一个版本修复，并用到本插件的最新版本中

**Comment by shyoshyo** [comment]
优雅的实现 233

**Comment by RikaSugisawa** [comment]
噗w刚刚发现有一个作业是-71分，就顺便查了查。
（有点好奇是怎么查出来这个对应关系的
