### ISSUE TITLE
课程公告乱码？

### ISSUE THREAD

**Issue by IcicleF** [xxr3376/Learn-Project#53]
空的公告内容显示为奇怪的东西，也不知道是不是个bug

![1](https://user-images.githubusercontent.com/26814565/54738499-7db82d80-4bef-11e9-8020-a721ad4fcec4.png)
![2](https://user-images.githubusercontent.com/26814565/54738501-7db82d80-4bef-11e9-8c9c-c73133c63759.png)

**Comment by Harry-Chen** [comment]
这是UTF-8的BOM，网络学堂使用了很迷的存储方式

**Comment by Harry-Chen** [comment]
更正：这不是 BOM，奇怪的字节是 `\xC2\x9E\xC3\xA9\x65`。目前对此毫无头绪，使用 workaround 的方式暂且认为是修复了。
