### ISSUE TITLE
讨论区标题出现html字符

### ISSUE THREAD

**Issue by heheda12345** [xxr3376/Learn-Project#57]
![image](https://user-images.githubusercontent.com/25218289/55472220-229a2800-563e-11e9-9971-2dd81887675c.png)
![image](https://user-images.githubusercontent.com/25218289/55472259-3e9dc980-563e-11e9-89a2-7a3631df72ab.png)

**Comment by Harry-Chen** [comment]
讨论区的标题没有被 escape 过
