### ISSUE TITLE
讨论区帖子过多时超出了底部

### ISSUE THREAD

**Issue by bl0** [xxr3376/Learn-Project#59]
如图，讨论区帖子过多时超过了底部，看了一下网络学堂里没有这个问题。
![image](https://user-images.githubusercontent.com/9164121/57822156-a7439e80-77c5-11e9-876b-11b9aeb98c6f.png)

**Comment by Harry-Chen** [comment]
应该是网络学堂的CSS有问题，在frame中计算会产生错误

**Comment by Harry-Chen** [comment]
这个问题我暂时无法复现…因此先搁置一下

**Comment by Harry-Chen** [comment]
目前无法复现，暂时先 close，遇到问题再 reopen
