### ISSUE TITLE
建议：一键下载功能 能否根据课程将下载的文件分文件夹保存

### ISSUE THREAD

**Issue by RyanWei0224** [xxr3376/Learn-Project#62]
或者加上不同的前缀/后缀也行
emmm因为一次下载几十个文件实在是不好分辨哪个是属于哪个课程的。。。
麻烦作者啦

**Comment by Harry-Chen** [comment]
这里有一个不好实现的问题，我事实上不知道这些附件的文件名，所以是直接调用浏览器 API 告知它下载的。

**Comment by Harry-Chen** [comment]
以及 API 也没有指定存放位置的功能

**Comment by RyanWei0224** [comment]
抱歉，是我zz了，可以仅下载一节课的全部文件。。。
麻烦你们了
