### ISSUE TITLE
badge 数量应忽略隐藏项

### ISSUE THREAD

**Issue by robertying** [xxr3376/Learn-Project#63]
即使隐藏了某课的作业，在“项目汇总”的“所有作业”以及插件在 Chrome 菜单栏的图标仍会显示包含该课作业数量的 badge。

例：实验室科研探究 100 多项作业。

**Comment by Harry-Chen** [comment]
事实上已经忽略了这些内容 https://github.com/xxr3376/Learn-Project/blob/master/src/components/SummaryList.tsx#L77
不知道你指的是不是手动隐藏了单个内容

**Comment by robertying** [comment]
这是隐藏项设置：

隐藏了课程作业
![image](https://user-images.githubusercontent.com/22592111/65337439-b8c90700-dbfa-11e9-8335-f3953950f553.png)

这是依旧显示作业数的 badge：
![image](https://user-images.githubusercontent.com/22592111/65337474-ced6c780-dbfa-11e9-8993-62b076789bf1.png)

这是左侧菜单显示的作业数：
![image](https://user-images.githubusercontent.com/22592111/65337488-d5fdd580-dbfa-11e9-945a-8a2269d00a55.png)

**Comment by Harry-Chen** [comment]
等待进一步调查
