### ISSUE TITLE
无法正确处理退课

### ISSUE THREAD

**Issue by heheda12345** [xxr3376/Learn-Project#64]
清除数据，重新登录之后能恢复正常
![error](https://user-images.githubusercontent.com/25218289/65294080-08beb400-db90-11e9-93a0-3cb485033dd7.PNG)

**Comment by Harry-Chen** [comment]
（整整退了两门课才）定位到了问题。

https://github.com/xxr3376/Learn-Project/blob/master/src/components/SummaryList.tsx#L77

当退课以后，`contentIgnore` 中对应的课程部分就已经被清空，所以计数时会发生错误。

**Comment by Harry-Chen** [comment]
一般来说刷新页面可以解决，如果不能解决那么应该还有问题。
