### ISSUE TITLE
建议：对作业按照截止日期排序

### ISSUE THREAD

**Issue by rzswh** [xxr3376/Learn-Project#65]
现在貌似是按照作业生效时间排序，感觉不太友好，可以改进一下w
建议按如下方式排序：未提交未截止作业（截止时间从早到晚）、已提交作业和已截止作业（按截止日期从晚到早）

**Comment by renzibei** [comment]
+1

**Comment by Harry-Chen** [comment]
看起来的确是描述的问题，做排序的时候出了一些问题，可见 https://github.com/xxr3376/Learn-Project/commit/d4a402ef584a094aabcdb8f58d826a2e265891cb#diff-57e7216969609c9b5aaccf60f53e79cbR67-R74
