### ISSUE TITLE
建议：根据google账户对已读信息进行同步

### ISSUE THREAD

**Issue by zhaoxh16** [xxr3376/Learn-Project#67]
在轮流不同电脑使用相同google账户登录网络学堂时，需要判断哪些信息读过哪些信息没有读过。可否将已读信息根据网络学堂账号或者google账号同步呢？

**Comment by Harry-Chen** [comment]
考虑过使用 Chrome 提供的同步存储区的功能，但是因为 quota 太少，所以后来放弃了

**Comment by Harry-Chen** [comment]
目前 Google Chrome 提供的同步 quota 还是相当小，如果全部存进去的话，可能会导致课程比较多的用户工作异常，所以保险起见就干脆都不存了。
