### ISSUE TITLE
建议：一键/自动重新获取 session

### ISSUE THREAD

**Issue by dramforever** [xxr3376/Learn-Project#69]
有时点开作业详细信息看着做作业，做完作业点提交的时候加载网络学堂的页面时发现登录的 session 已经超时了，所以如果要交只能：

- 刷新，重新找到作业，或者
- 点开一个新的 learn helper 让它获取 session，关掉，点一个别的公告啥的，然后再点原来要交的作业的提交

希望可以在点击提交的时候如果 session 超时自动重新登录，或者放个重新获取 session 的按钮之类的。

（在超时的条件下疑似“手动刷新”会登录失败且重试也不管用，但是刷新和新开的 instance 正常，这点待确认和验证。）

**Comment by Harry-Chen** [comment]
这里有个问题…网络学堂 session 过期它还是返回 200
手动刷新没用是因为它不会触发登录，不过这个可以加上
