### ISSUE TITLE
Firefox点击下载文件下载内容是downloadFile

### ISSUE THREAD

**Issue by AkkoDiana** [xxr3376/Learn-Project#71]
点击这个下载文件后
<img width="387" alt="截屏2020-02-2214 03 51" src="https://user-images.githubusercontent.com/37377591/75087509-40d18500-557c-11ea-8e43-131b53a28d5c.png">
下载内容是这样的
<img width="475" alt="截屏2020-02-2214 04 03" src="https://user-images.githubusercontent.com/37377591/75087515-52b32800-557c-11ea-98fb-e6a6e5bac915.png">
而非对应的文件，但是文件大小却是正确的
环境是：Firefox 73.0.1 macOS Catalina 10.15.3

**Comment by Harry-Chen** [comment]
确实，https://github.com/xxr3376/Learn-Project/blob/master/src/components/ContentCard.tsx#L266 忘记传入 `attachmentName` 了，下一个版本修复吧。

**Comment by Harry-Chen** [comment]
目前看起来，作业里面的文件能够获取到文件名，但是老师上传的文件并不能

**Comment by Harry-Chen** [comment]
很奇怪firefox不能自动根据 HTTP Header 重命名文件

**Comment by Harry-Chen** [comment]
Partially fixed in https://github.com/xxr3376/Learn-Project/commit/c26acf37445950a5ec05db7630ef118c94141986 and included in v4.2.1
