### ISSUE TITLE
功能请求：加入课程文件预览

### ISSUE THREAD

**Issue by 111116** [xxr3376/Learn-Project#72]
网络学堂中课程文件右侧有一个iframe，点击之后可以预览该文件的内容。希望 Learn Helper 也可以在课程文件的文件详情页面上加入这个功能

**Comment by Harry-Chen** [comment]
查看了一下，嵌入 `https://learn.tsinghua.edu.cn/f/wlxt/kc/wj_wjb/student/beforePlay?sfgk=0&wjid=${file.id}&mk=mk_kcwj&pageType=all&browser=-1` 即可

**Comment by Harry-Chen** [comment]
教师端为 `https://learn.tsinghua.edu.cn/f/wlxt/kc/wj_wjb/teacher/beforePlay?wjid=${file.id}&mk=mk_kcwj&sfgk=0&browser=-1`

**Comment by 111116** [comment]
这个iframe在点击之前显示的是文件封面 `pageType=first`，点击之后加载全部内容`pageType=all`

**Comment by Harry-Chen** [comment]
fixed by c26acf37445950a5ec05db7630ef118c94141986 and included in v4.2.1
