### ISSUE TITLE
mac上的Chrome无法使用

### ISSUE THREAD

**Issue by Azure-Vision** [xxr3376/Learn-Project#80]
![image](https://user-images.githubusercontent.com/23475597/90736534-70c9cd00-e300-11ea-9867-0dc1754135f1.png)
mac上的Chrome浏览器打开并登陆后只会显示如上界面

**Comment by Harry-Chen** [comment]
请给出 Chrome 版本，Network 里面的网络请求和控制台日志

**Comment by Azure-Vision** [comment]
Chrome 版本： 84.0.4147.135
Network 里面的网络请求：
![image](https://user-images.githubusercontent.com/23475597/91018748-8c93e280-e622-11ea-8ee8-775abbf95448.png)
![image](https://user-images.githubusercontent.com/23475597/91018801-9cabc200-e622-11ea-9bb8-7147bf4f03c1.png)
控制台日志：
` action persist/PERSIST @ 15:53:25.383
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}}
index.js:1  action     {type: "persist/PERSIST", register: ƒ, rehydrate: ƒ}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action persist/REHYDRATE @ 15:53:25.393
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "persist/REHYDRATE", payload: {…}, err: undefined, key: "data_redux"}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1 Migration not necessary.
index.js:1  action UI/login_dialog_visibility @ 15:53:25.583
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/login_dialog_visibility", state: true}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action UI/login_dialog_progress @ 15:53:43.523
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/login_dialog_progress", state: true}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action UI/snackbar_content @ 15:53:46.528
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/snackbar_content", snackbarContent: "登录失败：登录超时", snackbarType: "snack_bar_error"}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action UI/snackbar_visibility @ 15:53:46.531
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/snackbar_visibility", state: true}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action UI/login_dialog_visibility @ 15:53:46.533
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/login_dialog_visibility", state: false}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action UI/login_dialog_progress @ 15:53:46.534
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/login_dialog_progress", state: false}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1 login failed: not logged in or login timeout
index.js:1  action UI/login_dialog_visibility @ 15:53:46.562
index.js:1  prev state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}
index.js:1  action     {type: "UI/login_dialog_visibility", state: true}
index.js:1  next state {ui: {…}, helper: {…}, data: {…}, _persist: {…}}`

**Comment by Azure-Vision** [comment]
啊这，现在已经可以使用了
