### ISSUE TITLE
Chrome 85 下部分课程文件预览显示不能

### ISSUE THREAD

**Issue by jiegec** [xxr3376/Learn-Project#81]
见 https://www.chromestatus.com/feature/5088147346030592

现象：第一次点击课程文件可以预览，之后的点击大概率不能预览。不能预览的请求，都没有 Cookie 。

**Comment by jiegec** [comment]
设置 chrome://flags/#same-site-by-default-cookies 为 Disabled 可以绕过这个问题。

**Comment by Harry-Chen** [comment]
根据 Chrome 的同源策略，在有权限访问某个站点的插件中嵌入的该站点的 iframe 也会被认为和该站点同源，所以这个问题不应该发生。此外，用户反馈“刷新之后第一次点击是好的”，考虑是 Chrome 的某种实现 bug。

**Comment by Harry-Chen** [comment]
Add workaround in c1a021a6327227bd957551ce92908bc665fa46a1
