### ISSUE TITLE
密码正确但仍然需要重新输入凭据

### ISSUE THREAD

**Issue by leezy233** [xxr3376/Learn-Project#82]
不知道是否是我操作的问题。
如果不勾选“保存凭据以自动登录”的话，即使输入用户名和密码正确显示登录成功，仍然会继续弹出“更新凭据窗口”。勾选“保存凭据以自动登录”则不出现此问题。（win10+最新版chrome）

![learn helper bug](https://user-images.githubusercontent.com/41156182/93018153-3eaa4300-f600-11ea-9c21-00be03e3cff9.png)

**Comment by Harry-Chen** [comment]
确实是 bug，不过我最近一段时间没空继续修复了。先使用保存凭据，用完退出吧 😢
