### ISSUE TITLE
出现声称是不可恢复但实际刷新就能解决的错误

### ISSUE THREAD

**Issue by IcicleF** [xxr3376/Learn-Project#84]
如题，在进入Learn Helper时，偶尔会声称出现“不可恢复的错误”：

```
TypeError: Cannot read property 'includes' of undefined
```

但在刷新一次后即可解决。

目前不清楚如何复现，但是印象中均是在首次打开Learn Helper时出现此问题；问题已在多台计算机上的Edge浏览器上出现，各个Edge之间的设置彼此同步。

**Comment by Harry-Chen** [comment]
不可恢复是对于那一次特定的 launch 来说没救了 = =
是因为我 migration 没写对，所以从新版本升级 / 新安装一定会挂，下一个版本会修，但是反正刷新就好了就懒得马上发版本了

**Comment by IcicleF** [comment]
草，关键是那么大一个清除数据按钮摆在那。
希望加个文字提示让我先刷新试试
