### ISSUE TITLE
作业页面显示的图标不对齐

### ISSUE THREAD

**Issue by Starrah** [xxr3376/Learn-Project#85]
如下图。
环境：Win10，Chrome 85.0.4183.102，Learn Helper v4.3.0
虽然事实上其实并不影响使用\doge\doge
![QQ截图20200921203914](https://user-images.githubusercontent.com/46821571/93767474-aa1c9200-fc4a-11ea-92ca-dde8cd7a3118.png)

**Comment by Harry-Chen** [comment]
material ui 更新之后 CSS 好像有一些失效了，下个版本修吧

**Comment by Starrah** [comment]
已经定位问题并提交PR #86 ~

**Comment by Harry-Chen** [comment]
Fixed in #86, thanks!
