### ISSUE TITLE
SameSite=Lax by default cookies will cause 404 error in pages with iframe

### ISSUE THREAD

**Issue by jameslahm** [xxr3376/Learn-Project#87]
非常感谢开发这个项目！
`chrome`新版本已经对没有设置`SameSite`的cookie作第三方使用屏蔽处理，会导致含有网络学堂内嵌`iframe`的页面出现404。目前尝试可以通过`chrome://flags`，禁用掉`SameSite by default cookies`解决。`firefox`新版本可能也有这个问题，应该可以通过`about:config`，禁用掉`network.cookie.sameSite.laxByDefault`解决。感觉如果可行的话，可以加到文档里~

**Comment by Harry-Chen** [comment]
不完全是这个问题，参见 #81 。

**Comment by Harry-Chen** [comment]
因为理论上来说，插件是需要被认为同源的，否则插件的网络请求就全部废掉了。

**Comment by jameslahm** [comment]
噢，是的，刚看到 https://www.chromium.org/updates/same-site/test-debug#TOC-Testing-Chrome-extensions
谢谢~
